### ISSUE TITLE
How do I run cucumber tests?

### ISSUE THREAD

**Issue by rahulvig** [rhpijnacker/intern-cucumber#12]
I am trying to run the tests locally. I have cloned the repo and I am having trouble on how to start the tests. I have tried running 

> npx cucumber

 and 

> npx intern-cucumber

none of them executes the tests correctly. Please help.

**Comment by rhpijnacker** [comment]
> npm run test
should do the trick

**Comment by rahulvig** [comment]
I am getting this error on running 

> npm run test

```
Error: Cannot find module '@dojo/shim/global'
  at Function.Module._resolveFilename  <internal/modules/cjs/loader.js:594:15>
  at Function.Module._load  <internal/modules/cjs/loader.js:520:25>
  at Module.require  <internal/modules/cjs/loader.js:650:17>
  at require  <internal/modules/cjs/helpers.js:20:18>
  at Object.<anonymous>  <node_modules/intern-cucumber/interface/cucumber.js:2:16>
  at Module._compile  <internal/modules/cjs/loader.js:702:30>
  at Object.Module._extensions..js  <internal/modules/cjs/loader.js:713:10>
  at Module.load  <internal/modules/cjs/loader.js:612:32>
  at tryModuleLoad  <internal/modules/cjs/loader.js:551:12>
  at Function.Module._load  <internal/modules/cjs/loader.js:543:3>
  at Module.require  <internal/modules/cjs/loader.js:650:17>
  at require  <internal/modules/cjs/helpers.js:20:18>
  at Object.<anonymous>  <node_modules/intern-cucumber/plugin.js:1:84>
  at Module._compile  <internal/modules/cjs/loader.js:702:30>
  at Object.Module._extensions..js  <internal/modules/cjs/loader.js:713:10>
  at Module.load  <internal/modules/cjs/loader.js:612:32>
```

**Comment by rahulvig** [comment]
Thank you! I got it working at last. But still facing some issue.
I am getting - 

> Error: "Given I open the company login page" failed:
>     function timed out, ensure the promise resolves within 5000 milliseconds

my intern.json has these entries-
```
{
	"capabilities": {
    "fixSessionCapabilities": false,
		"defaultTimeout": 90000
},

 "functionalTimeouts": {
	  "connectTimeout": 60000
 },
```

**Comment by rhpijnacker** [comment]
I'm not sure what the cause of that would be.
When I run the tests locally they just run fine.
